// RAG(Retrieval-Augmented Generation) 기법을 활용해 LLM의 한계를 확장
= Retrieval-Augmented Generation – 모델의 능력을 확장하기
include::_attributes.adoc[]

LLM은 매우 강력한 도구이지만, 그 능력은 결국 학습된 지식과 정보의 범위에 한정됩니다.  
결국 "아는 만큼만 대답할 수 있다"는 말이죠.  
그렇다면, 학습 데이터에 포함되지 않은 질문을 해야 할 경우는 어떻게 해야 할까요?  
혹은, 학습 데이터에 직접 포함되어 있지는 않지만, 관련 있는 질문이라면요?

이 문제를 해결하는 방법은 다양하며, 사용할 수 있는 자원과 시간 또는 비용에 따라 달라집니다. 몇 가지 방법은 다음과 같습니다:

- 필요한 정보를 포함하도록 모델을 **완전히 재학습**시키는 것.  
  하지만 이 방법은 수천 개의 GPU를 몇 주간 돌릴 수 있는 극소수의 기업만이 가능하죠.
  
- 새로운 정보를 이용해 모델을 **파인튜닝(fine-tuning)** 하는 것.  
  훨씬 적은 자원으로 몇 분에서 몇 시간 안에 가능하며, 특정 맥락이나 어휘에 대한 이해를 높이는 데는 효과적입니다.  
  하지만 완전한 재학습이 아니기 때문에, 새로운 정보가 정확히 통합되지 않을 수 있고,  
  정보를 더 추가할 때마다 모델을 다시 훈련하고 재배포해야 합니다.

- 새로운 정보를 데이터베이스에 저장하고, **질문과 관련 있는 정보만 검색해서 질문에 첨부한 후 LLM에 보내는 방법**.  
  이 기법이 바로 **Retrieval-Augmented Generation(RAG)** 입니다.  
  RAG는 모델을 재학습하거나 파인튜닝하지 않고도 새로운 지식을 활용할 수 있고,  
  지식의 갱신도 매우 간편하다는 점에서 매우 유용합니다.

우리는 이미 https://milvus.io/[Milvus,window=_blank]를 사용해 벡터 데이터베이스(Vector Database)를 준비해 두었고,  
그 안에 https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/[California Driver's Handbook,window=_blank]의 내용을  
https://www.ibm.com/topics/embedding[임베딩(Embedding),window=_blank] 형태로 저장해두었습니다.

이번 실습에서는 이 RAG 기법을 활용해 **보험 청구(Claim)에 관한 질문을 해보고**,  
이 새로운 지식을 모델을 변경하지 않고도 어떻게 활용할 수 있는지 체험해보겠습니다.

`parasol-insurance/lab-materials/03` 폴더로 이동한 뒤,  
`03-05-retrieval-augmented-generation.ipynb` 라는 이름의 노트북을 열고 지침을 따라 진행해 주세요.

실습이 끝나면 노트북을 닫고 다음 페이지로 넘어가면 됩니다.
